### ISSUE TITLE
Global decay function

### ISSUE THREAD

**Issue by knasen88** [DuduSandsten/WebDKP#4]
I've had an older version, and found this line so I've been using it for applying global decay and it's all been fine, but lately last 3 resets it seems to be inconsistent. It applies different % to different people. (mainly old players receiving less decay somehow)

-- Global decay function for the current DKP table.
-- Applies percentage based DKP decay to all entries in the table.
-- Using ceil so sub 10 dkp entries eventually dissipate to 0.
-- ================================

function WebDKP_ApplyGlobalDecay(rate)

    local player = {};

    if rate>1 or rate<=0 then
        WebDKP_Print("Bad decay rate. Rate should be within [0,1]. Use 0.1 to apply a 10% reduction for example.");
        return;
    end

    local tableid = WebDKP_GetTableid();

    for k, v in pairs(WebDKPDkpTable) do
        if ( type(v) == "table" and v["dkp"..tableid] >= 1) then
            player[0] = {
                    ["name"] = k,
                    ["class"] = v["class"],
                };
            WebDKPAddDKP((ceil(v["dkp"..tableid]rate)(-1)), k.." decay", "false", player)
        end

    end
end

I called on it using /script WebDKP_ApplyGlobalDecay(0.1)

You can look up the results on some decays here : https://webdkp.com/dkp/Elysium/illu+whatever/
(Ramlosa for example got 4dkp decay after having 200+) meanwhile some others got normal decays.
I'll update the addon but If the decay calculation is the same it might still persist?

If you could add me on discord for some support I'd be very thankful knasn#3063 (found no other way than this github or blog comment to actually contact you

**Comment by DuduSandsten** [comment]
Heya

I couldn't find that code in my fork. Does your minimap icon say **"Sandstens fork"** when you hover your cursor over it? If not then you have some other fork of WebDKP. 
![](https://i.imgur.com/XoVAN7Y.png)

[Maybe this one?](https://github.com/webdkpthroaway/WebDKP_Elysium/blob/607b3f4cabeae924629cdf8240c6a0ffabc17668/GroupFunctions.lua) (That one is not maintained by me) 
The feature of adding percentage dkp in my fork is done via the minimap icon menu. The other fork might be intentionally be hiding the feature because it's work in progress.

To try the percentage decay in my version get the latest version download from: 
https://github.com/DuduSandsten/WebDKP/archive/master.zip

You can see the code which I wrote for adding percentage DKP here 
https://github.com/DuduSandsten/WebDKP/blob/master/Awards.lua#L146

Best regards

**Comment by knasen88** [comment]
Yea it was hidden function inside the lua which i found when rummaging trough it. It seemed to work but now it doesnt anymore.
